USE [master]
GO

/****** Object:  Database [tecnun]    Script Date: 22/06/2018 12:22:50 ******/
DROP DATABASE [tecnun]
GO

/****** Object:  Database [tecnun]    Script Date: 22/06/2018 12:22:50 ******/
CREATE DATABASE [tecnun]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'tecnun', FILENAME = N'D:\Dev\Database\SQLServer\Data\tecnun.mdf' , SIZE = 24576KB , MAXSIZE = 921600KB , FILEGROWTH = 1024KB )
 LOG ON 
( NAME = N'tecnun_log', FILENAME = N'D:\Dev\Database\SQLServer\Data\tecnun_log.ldf' , SIZE = 22920KB , MAXSIZE = 1048576KB , FILEGROWTH = 10%)
GO

ALTER DATABASE [tecnun] SET COMPATIBILITY_LEVEL = 100
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [tecnun].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [tecnun] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [tecnun] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [tecnun] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [tecnun] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [tecnun] SET ARITHABORT OFF 
GO

ALTER DATABASE [tecnun] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [tecnun] SET AUTO_SHRINK ON 
GO

ALTER DATABASE [tecnun] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [tecnun] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [tecnun] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [tecnun] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [tecnun] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [tecnun] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [tecnun] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [tecnun] SET  DISABLE_BROKER 
GO

ALTER DATABASE [tecnun] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [tecnun] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [tecnun] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [tecnun] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [tecnun] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [tecnun] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [tecnun] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [tecnun] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [tecnun] SET  MULTI_USER 
GO

ALTER DATABASE [tecnun] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [tecnun] SET DB_CHAINING OFF 
GO

ALTER DATABASE [tecnun] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [tecnun] SET TARGET_RECOVERY_TIME = 0 SECONDS 
GO

ALTER DATABASE [tecnun] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [tecnun] SET QUERY_STORE = OFF
GO

USE [tecnun]
GO

ALTER DATABASE SCOPED CONFIGURATION SET MAXDOP = 0;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET MAXDOP = PRIMARY;
GO

ALTER DATABASE SCOPED CONFIGURATION SET LEGACY_CARDINALITY_ESTIMATION = OFF;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET LEGACY_CARDINALITY_ESTIMATION = PRIMARY;
GO

ALTER DATABASE SCOPED CONFIGURATION SET PARAMETER_SNIFFING = ON;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET PARAMETER_SNIFFING = PRIMARY;
GO

ALTER DATABASE SCOPED CONFIGURATION SET QUERY_OPTIMIZER_HOTFIXES = OFF;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET QUERY_OPTIMIZER_HOTFIXES = PRIMARY;
GO

ALTER DATABASE [tecnun] SET  READ_WRITE 
GO

