//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TPA.Services.Seguranca {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class SegurancaResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SegurancaResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TPA.Services.Seguranca.SegurancaResources", typeof(SegurancaResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CADASTRO_ACAO_ACESSAR.
        /// </summary>
        public static string CADASTRO_ACAO_ACESSAR {
            get {
                return ResourceManager.GetString("CADASTRO_ACAO_ACESSAR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CADASTRO_NODELABEL_ACESSAR.
        /// </summary>
        public static string CADASTRO_NODELABEL_ACESSAR {
            get {
                return ResourceManager.GetString("CADASTRO_NODELABEL_ACESSAR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CADASTRO_PERFIL_ACESSAR.
        /// </summary>
        public static string CADASTRO_PERFIL_ACESSAR {
            get {
                return ResourceManager.GetString("CADASTRO_PERFIL_ACESSAR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CADASTRO_PROJETO_ACESSAR.
        /// </summary>
        public static string CADASTRO_PROJETO_ACESSAR {
            get {
                return ResourceManager.GetString("CADASTRO_PROJETO_ACESSAR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CADASTRO_TIPOATIVIDADE_ACESSAR.
        /// </summary>
        public static string CADASTRO_TIPOATIVIDADE_ACESSAR {
            get {
                return ResourceManager.GetString("CADASTRO_TIPOATIVIDADE_ACESSAR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CADASTRO_USUARIO_ACESSAR.
        /// </summary>
        public static string CADASTRO_USUARIO_ACESSAR {
            get {
                return ResourceManager.GetString("CADASTRO_USUARIO_ACESSAR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EDITAR_ATIVIDADE.
        /// </summary>
        public static string EDITAR_ATIVIDADE {
            get {
                return ResourceManager.GetString("EDITAR_ATIVIDADE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GERENCIAR_ATIVIDADES_FUNCIONARIOS.
        /// </summary>
        public static string GERENCIAR_ATIVIDADES_FUNCIONARIOS {
            get {
                return ResourceManager.GetString("GERENCIAR_ATIVIDADES_FUNCIONARIOS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to JOBS.
        /// </summary>
        public static string JOBS {
            get {
                return ResourceManager.GetString("JOBS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MENU_ATIVIDADES.
        /// </summary>
        public static string MENU_ATIVIDADES {
            get {
                return ResourceManager.GetString("MENU_ATIVIDADES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MENU_CONFIGURACOES.
        /// </summary>
        public static string MENU_CONFIGURACOES {
            get {
                return ResourceManager.GetString("MENU_CONFIGURACOES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MENU_PROJETOS.
        /// </summary>
        public static string MENU_PROJETOS {
            get {
                return ResourceManager.GetString("MENU_PROJETOS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TESTES.
        /// </summary>
        public static string TESTES {
            get {
                return ResourceManager.GetString("TESTES", resourceCulture);
            }
        }
    }
}
