//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TPA.Infra {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ApplicationResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ApplicationResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TPA.Infra.ApplicationResources", typeof(ApplicationResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1.
        /// </summary>
        public static string NODELABEL_ADMINISTRATIVO_ID {
            get {
                return ResourceManager.GetString("NODELABEL_ADMINISTRATIVO_ID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ADMINISTRATIVO.
        /// </summary>
        public static string NODELABEL_ADMINISTRATIVO_NOME {
            get {
                return ResourceManager.GetString("NODELABEL_ADMINISTRATIVO_NOME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 3.
        /// </summary>
        public static string NODELABEL_AREA_ID {
            get {
                return ResourceManager.GetString("NODELABEL_AREA_ID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Area.
        /// </summary>
        public static string NODELABEL_AREA_NOME {
            get {
                return ResourceManager.GetString("NODELABEL_AREA_NOME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2.
        /// </summary>
        public static string NODELABEL_CLIENTE_ID {
            get {
                return ResourceManager.GetString("NODELABEL_CLIENTE_ID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cliente.
        /// </summary>
        public static string NODELABEL_CLIENTE_NOME {
            get {
                return ResourceManager.GetString("NODELABEL_CLIENTE_NOME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 5.
        /// </summary>
        public static string NODELABEL_ENTREGAVEIS_ID {
            get {
                return ResourceManager.GetString("NODELABEL_ENTREGAVEIS_ID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Entregaveis.
        /// </summary>
        public static string NODELABEL_ENTREGAVEIS_NOME {
            get {
                return ResourceManager.GetString("NODELABEL_ENTREGAVEIS_NOME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 6.
        /// </summary>
        public static string NODELABEL_ETAPAS_ID {
            get {
                return ResourceManager.GetString("NODELABEL_ETAPAS_ID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Etapas.
        /// </summary>
        public static string NODELABEL_ETAPAS_NOME {
            get {
                return ResourceManager.GetString("NODELABEL_ETAPAS_NOME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 4.
        /// </summary>
        public static string NODELABEL_PROJETO_ID {
            get {
                return ResourceManager.GetString("NODELABEL_PROJETO_ID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Projeto.
        /// </summary>
        public static string NODELABEL_PROJETO_NOME {
            get {
                return ResourceManager.GetString("NODELABEL_PROJETO_NOME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1.
        /// </summary>
        public static string PROJECTNODE_ADMINISTRATIVO_ID {
            get {
                return ResourceManager.GetString("PROJECTNODE_ADMINISTRATIVO_ID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ADMINISTRATIVO.
        /// </summary>
        public static string PROJECTNODE_ADMINISTRATIVO_NOME {
            get {
                return ResourceManager.GetString("PROJECTNODE_ADMINISTRATIVO_NOME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1.
        /// </summary>
        public static string TESTE {
            get {
                return ResourceManager.GetString("TESTE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1.
        /// </summary>
        public static string TIPOATIVIDADE_ATESTADO_ID {
            get {
                return ResourceManager.GetString("TIPOATIVIDADE_ATESTADO_ID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ATESTADO.
        /// </summary>
        public static string TIPOATIVIDADE_ATESTADO_NOME {
            get {
                return ResourceManager.GetString("TIPOATIVIDADE_ATESTADO_NOME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2.
        /// </summary>
        public static string TIPOATIVIDADE_FALTAJUSTIFICADA_ID {
            get {
                return ResourceManager.GetString("TIPOATIVIDADE_FALTAJUSTIFICADA_ID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FALTA JUSTIFICADA.
        /// </summary>
        public static string TIPOATIVIDADE_FALTAJUSTIFICADA_NOME {
            get {
                return ResourceManager.GetString("TIPOATIVIDADE_FALTAJUSTIFICADA_NOME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 3.
        /// </summary>
        public static string TIPOATIVIDADE_FERIAS_ID {
            get {
                return ResourceManager.GetString("TIPOATIVIDADE_FERIAS_ID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FERIAS.
        /// </summary>
        public static string TIPOATIVIDADE_FERIAS_NOME {
            get {
                return ResourceManager.GetString("TIPOATIVIDADE_FERIAS_NOME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 4.
        /// </summary>
        public static string TIPOATIVIDADE_FOLGAREMUNERADA_ID {
            get {
                return ResourceManager.GetString("TIPOATIVIDADE_FOLGAREMUNERADA_ID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FOLGA REMUNERADA.
        /// </summary>
        public static string TIPOATIVIDADE_FOLGAREMUNERADA_NOME {
            get {
                return ResourceManager.GetString("TIPOATIVIDADE_FOLGAREMUNERADA_NOME", resourceCulture);
            }
        }
    }
}
