// <auto-generated />
namespace TPA.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class correcaoindiceprojectnode : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(correcaoindiceprojectnode));
        
        string IMigrationMetadata.Id
        {
            get { return "201706241802318_correcao-indice-projectnode"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
