// <auto-generated />
namespace TPA.Infra.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class ProjectNodeDescricao_e_UsuarioEnviarAlertaLancamento : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(ProjectNodeDescricao_e_UsuarioEnviarAlertaLancamento));
        
        string IMigrationMetadata.Id
        {
            get { return "201712131705000_ProjectNode.Descricao_e_Usuario.EnviarAlertaLancamento"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return Resources.GetString("Source"); }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
