// <auto-generated />
namespace TPA.Infra.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class ProjectNodeDescricao_Criar_Campo : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(ProjectNodeDescricao_Criar_Campo));
        
        string IMigrationMetadata.Id
        {
            get { return "201712131710436_ProjectNode.Descricao_Criar_Campo"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
