// <auto-generated />
namespace TPA.Infra.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class usuarioativo : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(usuarioativo));
        
        string IMigrationMetadata.Id
        {
            get { return "201712081225249_usuario-ativo"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return Resources.GetString("Source"); }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
