// <auto-generated />
namespace TPA.Infra.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class tipoatividadesistema : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(tipoatividadesistema));
        
        string IMigrationMetadata.Id
        {
            get { return "201801151852339_tipo-atividade-sistema"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
